version: '3.3'
services:
        web:
                image: php:7.3-apache
        db:
                image: mysql:8.0
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: test_db
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
