version: '3.3'
services:
        web:
                build:
                        context: ./php
                        dockerfile: Dockerfile
                container_name: php73
                depends_on:
                        - db
                volumes:
                        - ./php:/var/www/html
                ports:
                        - 8001:80
        db:
                image: mysql:8.0
                container_name: mysql8
                restart: always
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - ./data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: tianxiang_db
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
                ports:
                        - 3306:3306
                expose:
                        - 3306
        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: phpmyadmin
                links:
                        - db:db
                ports:
                        - 8000:80
                environment:
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
                        MYSQL_ROOT_PASSWORD: root
